# Generated by Django 4.0.4 on 2022-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('MENTOR', 'mentor')], default='STUDENT', max_length=15),
        ),
    ]
