# Generated by Django 4.0.4 on 2022-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR', 'Mentor')], default='STUDENT', max_length=15),
        ),
    ]
