# Generated by Django 4.0.4 on 2022-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employee_is_mentor_alter_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR_OR_STUDENT', 'Mentor')], default='STUDENT', max_length=20),
        ),
    ]
