# Generated by Django 4.0.4 on 2022-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_employee_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_mentor',
        ),
    ]
