# Generated by Django 4.0.4 on 2022-05-07 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subjectlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlesson',
            name='video',
            field=models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
