# Generated by Django 4.0.4 on 2022-05-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subjectlesson_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectLesson',
        ),
    ]
