# Generated by Django 4.0.4 on 2022-05-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_subjectlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryuser',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
